### ISSUE TITLE
Add user log-in and profile system

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#204]
Oh, boy there are a lot of features to get right with this one. 

I really don't want to do it, but we have to in order to run Little Case bots and to have trusted curators that can do simple things like reset their passwords.

This is going to be a meta issue with a bunch of other issues we'll have to sort out:

 - [ ] [Set up email so we can send things](https://github.com/freelawproject/bigcases2/issues/199).

 - [ ] [Disable the CDN on login cookies](https://github.com/freelawproject/bigcases2/issues/200).

 - [ ] [Create a profile section](https://github.com/freelawproject/bigcases2/issues/201).

 - [ ] [Do all the user creation/password stuff](https://github.com/freelawproject/bigcases2/issues/202)

 - [ ] [Add a login / profile / logout button](https://github.com/freelawproject/bigcases2/issues/203)

**Comment by mlissner** [comment]
Eh. This issue is low value. Deleting.
